Cart page
SumitSaundadkar/Ecom-Screens pull request #13
Opened 2022-02-18 18:52 UTC by SumitSaundadkar

card page added.

2022-02-18 19:19 UTC, ashishkatiyar2404 requested changes
suggest some changes make them. thn your code looks good to go🚀

2022-02-18 19:19 UTC, ashishkatiyar2404 commented on screens/cart managment/carts.html
> +        <div class="cart_cont">
cont? 
cart__container you can give a full name so that it will be easy to understand.

2022-02-18 19:19 UTC, ashishkatiyar2404 commented on screens/cart managment/carts.html
> +	</div>
to much spacing
you can use prettier or beautify file extension for arrange in proper manner🙂

2022-02-18 19:19 UTC, ashishkatiyar2404 commented on screens/cart managment/catrs.css
> +    --body-color:#c5c7c9;
good naming.
one suggestion use hex code for all or use rgba for all but dont use diff diff color code(follow one)

2022-02-18 19:19 UTC, ashishkatiyar2404 commented on screens/cart managment/catrs.css
> +    .containr {
```suggestion
    .container {
```

2022-02-18 19:19 UTC, ashishkatiyar2404 commented on screens/cart managment/catrs.css
> +    nav {
use class variable for styling

2022-02-18 19:19 UTC, ashishkatiyar2404 commented on screens/cart managment/catrs.css
> +    .fa-search {
don't use direct font awesome naming class name give ur class. Sometimes what happens ki if you use the same icon in the diff page and you want to give diff styling so the later one will override.

2022-02-19 17:53 UTC, SumitSaundadkar commented on screens/cart managment/carts.html
> +	</div>
done.

2022-02-19 18:03 UTC, SumitSaundadkar commented on screens/cart managment/catrs.css
> +    nav {
ok

2022-02-19 18:52 UTC, TusharJade reviewed
Looks good to me just follow hex or rgb only one of them other than that evrything looks good

2022-02-20 15:33 UTC, SumitSaundadkar commented on screens/cart managment/catrs.css
> +    .fa-search {
ok.

2022-02-20 15:35 UTC, SumitSaundadkar commented on screens/cart managment/catrs.css
> +    --body-color:#c5c7c9;
ok.

2022-02-20 15:41 UTC, SumitSaundadkar commented on screens/cart managment/catrs.css
> +    .containr {
done.

2022-02-20 15:41 UTC, merged